[2022-08-03 12:50:16,982] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T12:40:00+00:00 [queued]>
[2022-08-03 12:50:17,019] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T12:40:00+00:00 [queued]>
[2022-08-03 12:50:17,020] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 12:50:17,020] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-03 12:50:17,021] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 12:50:17,048] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-03T12:40:00+00:00
[2022-08-03 12:50:17,053] {standard_task_runner.py:51} INFO - Started process 25334 to run task
[2022-08-03 12:50:17,060] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'my_simple_dag', 'respond', '2022-08-03T12:40:00+00:00', '--job-id', '1080', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_simple_dag.py', '--cfg-path', '/tmp/tmpxkz4_9tc']
[2022-08-03 12:50:17,067] {standard_task_runner.py:76} INFO - Job 1080: Subtask respond
[2022-08-03 12:50:17,198] {logging_mixin.py:103} INFO - Running <TaskInstance: my_simple_dag.respond 2022-08-03T12:40:00+00:00 [running]> on host b4dcda255553
[2022-08-03 12:50:17,467] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T12:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T12:40:00+00:00
[2022-08-03 12:50:17,469] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-03 12:50:17,738] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=my_simple_dag, task_id=respond, execution_date=20220803T124000, start_date=20220803T125016, end_date=20220803T125017
[2022-08-03 12:50:17,873] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-03 12:50:17,908] {local_task_job.py:118} INFO - Task exited with return code 0
