[2022-08-03 12:30:14,844] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T12:20:00+00:00 [queued]>
[2022-08-03 12:30:15,063] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T12:20:00+00:00 [queued]>
[2022-08-03 12:30:15,063] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 12:30:15,064] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-03 12:30:15,065] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 12:30:15,084] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-03T12:20:00+00:00
[2022-08-03 12:30:15,090] {standard_task_runner.py:51} INFO - Started process 18873 to run task
[2022-08-03 12:30:15,097] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'my_simple_dag', 'respond', '2022-08-03T12:20:00+00:00', '--job-id', '1062', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_simple_dag.py', '--cfg-path', '/tmp/tmpded0vhc8']
[2022-08-03 12:30:15,102] {standard_task_runner.py:76} INFO - Job 1062: Subtask respond
[2022-08-03 12:30:15,186] {logging_mixin.py:103} INFO - Running <TaskInstance: my_simple_dag.respond 2022-08-03T12:20:00+00:00 [running]> on host b4dcda255553
[2022-08-03 12:30:15,268] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T12:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T12:20:00+00:00
[2022-08-03 12:30:15,270] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-03 12:30:15,319] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=my_simple_dag, task_id=respond, execution_date=20220803T122000, start_date=20220803T123014, end_date=20220803T123015
[2022-08-03 12:30:15,366] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-03 12:30:15,388] {local_task_job.py:118} INFO - Task exited with return code 0
