[2022-08-03 13:30:14,894] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T13:20:00+00:00 [queued]>
[2022-08-03 13:30:14,926] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T13:20:00+00:00 [queued]>
[2022-08-03 13:30:14,927] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 13:30:14,928] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-03 13:30:14,928] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 13:30:14,955] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-03T13:20:00+00:00
[2022-08-03 13:30:14,960] {standard_task_runner.py:51} INFO - Started process 10684 to run task
[2022-08-03 13:30:14,967] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'my_simple_dag', 'respond', '2022-08-03T13:20:00+00:00', '--job-id', '1116', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_simple_dag.py', '--cfg-path', '/tmp/tmp7m3511no']
[2022-08-03 13:30:14,973] {standard_task_runner.py:76} INFO - Job 1116: Subtask respond
[2022-08-03 13:30:15,079] {logging_mixin.py:103} INFO - Running <TaskInstance: my_simple_dag.respond 2022-08-03T13:20:00+00:00 [running]> on host b4dcda255553
[2022-08-03 13:30:15,226] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T13:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T13:20:00+00:00
[2022-08-03 13:30:15,227] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-03 13:30:15,274] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=my_simple_dag, task_id=respond, execution_date=20220803T132000, start_date=20220803T133014, end_date=20220803T133015
[2022-08-03 13:30:15,313] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-03 13:30:15,338] {local_task_job.py:118} INFO - Task exited with return code 0
