[2022-08-03 16:30:11,238] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T16:20:00+00:00 [queued]>
[2022-08-03 16:30:11,272] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: my_simple_dag.respond 2022-08-03T16:20:00+00:00 [queued]>
[2022-08-03 16:30:11,273] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:30:11,273] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-03 16:30:11,274] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:30:11,289] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-03T16:20:00+00:00
[2022-08-03 16:30:11,293] {standard_task_runner.py:51} INFO - Started process 29180 to run task
[2022-08-03 16:30:11,299] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'my_simple_dag', 'respond', '2022-08-03T16:20:00+00:00', '--job-id', '1278', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_simple_dag.py', '--cfg-path', '/tmp/tmp90ag_8__']
[2022-08-03 16:30:11,303] {standard_task_runner.py:76} INFO - Job 1278: Subtask respond
[2022-08-03 16:30:11,386] {logging_mixin.py:103} INFO - Running <TaskInstance: my_simple_dag.respond 2022-08-03T16:20:00+00:00 [running]> on host b4dcda255553
[2022-08-03 16:30:11,490] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T16:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T16:20:00+00:00
[2022-08-03 16:30:11,492] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-03 16:30:11,534] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=my_simple_dag, task_id=respond, execution_date=20220803T162000, start_date=20220803T163011, end_date=20220803T163011
[2022-08-03 16:30:11,583] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-03 16:30:11,591] {local_task_job.py:118} INFO - Task exited with return code 0
